// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigracijaNaBazu.Data;

#nullable disable

namespace MigracijaNaBazu.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Admin", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("Admini");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Atrakcija", b =>
                {
                    b.Property<int>("AtrakcijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtrakcijaId"));

                    b.Property<int>("KoordinateId")
                        .HasColumnType("int");

                    b.Property<string>("NazivAtrakcije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisAtrakcije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmartPlannerPlanId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaAtrakcije")
                        .HasColumnType("int");

                    b.HasKey("AtrakcijaId");

                    b.HasIndex("KoordinateId");

                    b.HasIndex("SmartPlannerPlanId");

                    b.ToTable("Atrakcije");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("KoordinateId")
                        .HasColumnType("int");

                    b.Property<string>("NazivEventa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisEventa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmartPlannerPlanId")
                        .HasColumnType("int");

                    b.Property<string>("StranicaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VrijemePocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemeZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("VrstaEventa")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("KoordinateId");

                    b.HasIndex("SmartPlannerPlanId");

                    b.ToTable("Eventi");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Koordinate", b =>
                {
                    b.Property<int>("KoordinateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoordinateId"));

                    b.Property<double>("Latituda")
                        .HasColumnType("float");

                    b.Property<double>("Longituda")
                        .HasColumnType("float");

                    b.HasKey("KoordinateId");

                    b.ToTable("Koordinate");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Newsletter", b =>
                {
                    b.Property<int>("NewsletterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsletterId"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperaterId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsletterId");

                    b.HasIndex("OperaterId");

                    b.ToTable("Newsletteri");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Operater", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperaterId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("Operateri");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Preferencija", b =>
                {
                    b.Property<int>("PreferencijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferencijaId"));

                    b.Property<int>("Historija")
                        .HasColumnType("int");

                    b.Property<int>("Kultura")
                        .HasColumnType("int");

                    b.Property<int>("NocniZivot")
                        .HasColumnType("int");

                    b.Property<int>("Priroda")
                        .HasColumnType("int");

                    b.Property<int>("TradicionalnaHrana")
                        .HasColumnType("int");

                    b.HasKey("PreferencijaId");

                    b.ToTable("Preferencije");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Recenzija", b =>
                {
                    b.Property<int>("RecenzijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecenzijaId"));

                    b.Property<int?>("AtrakcijaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.Property<int>("RegistrovaniKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UgostiteljskiObjekatId")
                        .HasColumnType("int");

                    b.HasKey("RecenzijaId");

                    b.HasIndex("AtrakcijaId");

                    b.HasIndex("RegistrovaniKorisnikId");

                    b.HasIndex("UgostiteljskiObjekatId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.RegistrovaniKorisnik", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KoordinateId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("NewsletterId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.HasIndex("KoordinateId");

                    b.HasIndex("NewsletterId");

                    b.ToTable("RegistrovaniKorisnici");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.SmartPlanner", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreferencijaId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrovaniKorisnikId")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.HasIndex("PreferencijaId");

                    b.HasIndex("RegistrovaniKorisnikId");

                    b.ToTable("SmartPlanneri");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.UgostiteljskiObjekat", b =>
                {
                    b.Property<int>("ObjekatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjekatId"));

                    b.Property<int>("KoordinateId")
                        .HasColumnType("int");

                    b.Property<string>("NazivObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmartPlannerPlanId")
                        .HasColumnType("int");

                    b.Property<int>("VrstaObjekta")
                        .HasColumnType("int");

                    b.HasKey("ObjekatId");

                    b.HasIndex("KoordinateId");

                    b.HasIndex("SmartPlannerPlanId");

                    b.ToTable("UgostiteljskiObjekti");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Atrakcija", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Koordinate", "Koordinate")
                        .WithMany()
                        .HasForeignKey("KoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigracijaNaBazu.Models.SmartPlanner", null)
                        .WithMany("ListaAtrakcija")
                        .HasForeignKey("SmartPlannerPlanId");

                    b.Navigation("Koordinate");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Event", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Koordinate", "Koordinate")
                        .WithMany()
                        .HasForeignKey("KoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigracijaNaBazu.Models.SmartPlanner", null)
                        .WithMany("ListaEvenata")
                        .HasForeignKey("SmartPlannerPlanId");

                    b.Navigation("Koordinate");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Newsletter", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Operater", "Operater")
                        .WithMany("Newsletteri")
                        .HasForeignKey("OperaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operater");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Recenzija", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Atrakcija", "Atrakcija")
                        .WithMany("Recenzije")
                        .HasForeignKey("AtrakcijaId");

                    b.HasOne("MigracijaNaBazu.Models.RegistrovaniKorisnik", "RegistrovaniKorisnik")
                        .WithMany("ListaRecenzija")
                        .HasForeignKey("RegistrovaniKorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigracijaNaBazu.Models.UgostiteljskiObjekat", "UgostiteljskiObjekat")
                        .WithMany("Recenzije")
                        .HasForeignKey("UgostiteljskiObjekatId");

                    b.Navigation("Atrakcija");

                    b.Navigation("RegistrovaniKorisnik");

                    b.Navigation("UgostiteljskiObjekat");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.RegistrovaniKorisnik", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Koordinate", "Koordinate")
                        .WithMany()
                        .HasForeignKey("KoordinateId");

                    b.HasOne("MigracijaNaBazu.Models.Newsletter", null)
                        .WithMany("Primaoci")
                        .HasForeignKey("NewsletterId");

                    b.Navigation("Koordinate");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.SmartPlanner", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Preferencija", "Preferencija")
                        .WithMany()
                        .HasForeignKey("PreferencijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigracijaNaBazu.Models.RegistrovaniKorisnik", "RegistrovaniKorisnik")
                        .WithMany("Planovi")
                        .HasForeignKey("RegistrovaniKorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preferencija");

                    b.Navigation("RegistrovaniKorisnik");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.UgostiteljskiObjekat", b =>
                {
                    b.HasOne("MigracijaNaBazu.Models.Koordinate", "Koordinate")
                        .WithMany()
                        .HasForeignKey("KoordinateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigracijaNaBazu.Models.SmartPlanner", null)
                        .WithMany("ListaObjekata")
                        .HasForeignKey("SmartPlannerPlanId");

                    b.Navigation("Koordinate");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Atrakcija", b =>
                {
                    b.Navigation("Recenzije");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Newsletter", b =>
                {
                    b.Navigation("Primaoci");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.Operater", b =>
                {
                    b.Navigation("Newsletteri");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.RegistrovaniKorisnik", b =>
                {
                    b.Navigation("ListaRecenzija");

                    b.Navigation("Planovi");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.SmartPlanner", b =>
                {
                    b.Navigation("ListaAtrakcija");

                    b.Navigation("ListaEvenata");

                    b.Navigation("ListaObjekata");
                });

            modelBuilder.Entity("MigracijaNaBazu.Models.UgostiteljskiObjekat", b =>
                {
                    b.Navigation("Recenzije");
                });
#pragma warning restore 612, 618
        }
    }
}
