// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gosarajevovol3.Data;

#nullable disable

namespace gosarajevovol3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507202318_UpdateUserHierarchyAndMissingTables")]
    partial class UpdateUserHierarchyAndMissingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gosarajevovol3.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttractionDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AttractionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AttractionType")
                        .HasColumnType("int");

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SmartPlannerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("SmartPlannerId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmartPlannerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("SmartPlannerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Hospitality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HospitalityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HospitalityType")
                        .HasColumnType("int");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SmartPlannerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("SmartPlannerId");

                    b.ToTable("Hospitality");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Culture")
                        .HasColumnType("int");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<int>("Nightlife")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredUserId")
                        .HasColumnType("int");

                    b.Property<int>("TraditionalFood")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredUserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HospitalityId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalityId");

                    b.HasIndex("RegisteredUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("gosarajevovol3.Models.SmartPlanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceId");

                    b.HasIndex("RegisteredUserId");

                    b.ToTable("SmartPlanners");
                });

            modelBuilder.Entity("gosarajevovol3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("gosarajevovol3.Models.Admin", b =>
                {
                    b.HasBaseType("gosarajevovol3.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Operator", b =>
                {
                    b.HasBaseType("gosarajevovol3.Models.User");

                    b.HasDiscriminator().HasValue("Operator");
                });

            modelBuilder.Entity("gosarajevovol3.Models.RegisteredUser", b =>
                {
                    b.HasBaseType("gosarajevovol3.Models.User");

                    b.HasDiscriminator().HasValue("RegisteredUser");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Attraction", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Coordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gosarajevovol3.Models.SmartPlanner", null)
                        .WithMany("Attractions")
                        .HasForeignKey("SmartPlannerId");

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Event", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Coordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gosarajevovol3.Models.SmartPlanner", null)
                        .WithMany("Events")
                        .HasForeignKey("SmartPlannerId");

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Hospitality", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Coordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gosarajevovol3.Models.SmartPlanner", null)
                        .WithMany("HospitalitySites")
                        .HasForeignKey("SmartPlannerId");

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Newsletter", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Operator", "Operator")
                        .WithMany("Newsletters")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Preference", b =>
                {
                    b.HasOne("gosarajevovol3.Models.RegisteredUser", "RegisteredUser")
                        .WithOne("Preference")
                        .HasForeignKey("gosarajevovol3.Models.Preference", "RegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Review", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Hospitality", "Hospitality")
                        .WithMany("Reviews")
                        .HasForeignKey("HospitalityId");

                    b.HasOne("gosarajevovol3.Models.RegisteredUser", "RegisteredUser")
                        .WithMany("ReviewList")
                        .HasForeignKey("RegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospitality");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("gosarajevovol3.Models.SmartPlanner", b =>
                {
                    b.HasOne("gosarajevovol3.Models.Preference", "Preference")
                        .WithMany()
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gosarajevovol3.Models.RegisteredUser", "RegisteredUser")
                        .WithMany("PlannerList")
                        .HasForeignKey("RegisteredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preference");

                    b.Navigation("RegisteredUser");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Hospitality", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("gosarajevovol3.Models.SmartPlanner", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Events");

                    b.Navigation("HospitalitySites");
                });

            modelBuilder.Entity("gosarajevovol3.Models.Operator", b =>
                {
                    b.Navigation("Newsletters");
                });

            modelBuilder.Entity("gosarajevovol3.Models.RegisteredUser", b =>
                {
                    b.Navigation("PlannerList");

                    b.Navigation("Preference");

                    b.Navigation("ReviewList");
                });
#pragma warning restore 612, 618
        }
    }
}
